export const products = [
	{
		id: 1,
		name: 'Spider',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 1000,
		img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Spiderman.JPG/640px-Spiderman.JPG',
		piece: 'В наличии: 3',
		thumbnails: [
			'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Spiderman.JPG/640px-Spiderman.JPG',
			'https://cdn-uploads.gameblog.fr/img/news/425341_645e546f4ddec.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 2,
		name: 'Batman',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 800,
		img: 'https://media1.popsugar-assets.com/files/thumbor/rThpfVdJzMRcQWvlnlbskYGUSSU=/fit-in/792x528/top/filters:format_auto():upscale()/2022/03/04/966/n/1922283/tmp_YDoQMc_eba3e322cfc57f83_MCDBATM_WB059.jpg',
		piece: 'В наличии: 2',
		thumbnails: [
			'https://media1.popsugar-assets.com/files/thumbor/rThpfVdJzMRcQWvlnlbskYGUSSU=/fit-in/792x528/top/filters:format_auto():upscale()/2022/03/04/966/n/1922283/tmp_YDoQMc_eba3e322cfc57f83_MCDBATM_WB059.jpg',
			'https://imageio.forbes.com/blogs-images/davidthier/files/2015/06/maxresdefault1.jpg?height=400&width=711&fit=bounds',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 3,
		name: 'Superman',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 700,
		img: 'https://images.immediate.co.uk/production/volatile/sites/3/2022/12/MCDBAVVEC017-d4ece24.jpg?quality=90&resize=980,654',
		piece: 'В наличии: 4 ',
		thumbnails: [
			'https://images.immediate.co.uk/production/volatile/sites/3/2022/12/MCDBAVVEC017-d4ece24.jpg?quality=90&resize=980,654',
			'https://ew.com/thmb/IWTSy6GrKCmZBSIcZwC84oHmNdw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mos-10175c_2-2000-116d947875b84ddcabb01baa1fa1b389.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 4,
		name: 'Capitan America',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/05/hipertextual-avengers-endgame-futuro-capitan-america-2019781893-scaled.jpg?fit=2560%2C1600&quality=50&strip=all&ssl=1',
		piece: 'В наличии: 1',
		thumbnails: [
			'https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/05/hipertextual-avengers-endgame-futuro-capitan-america-2019781893-scaled.jpg?fit=2560%2C1600&quality=50&strip=all&ssl=1',
			'https://media-assets.wired.it/photos/615f38375b820b8db3e7d14b/master/w_1600%2Cc_limit/1538729691_25CHRISEVANS4-jumbo.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 5,
		name: 'Thor',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://cdn.britannica.com/73/182873-050-E1C686F4/Chris-Hemsworth-Thor-Thor-The-Dark-World.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://cdn.britannica.com/73/182873-050-E1C686F4/Chris-Hemsworth-Thor-Thor-The-Dark-World.jpg',
			'https://images.squarespace-cdn.com/content/v1/5fbc4a62c2150e62cfcb09aa/1621312752468-LNQ5D4XJNMZ0UOCDGEH1/Thor.png',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 6,
		name: 'Dart Vader',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://lumiere-a.akamaihd.net/v1/images/image_67b709e4.jpeg?region=0,0,1536,864&width=768',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://lumiere-a.akamaihd.net/v1/images/image_67b709e4.jpeg?region=0,0,1536,864&width=768',
			'https://ew.com/thmb/DR9B7S2D_xzQSnXZKvy7E1-9BKA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/star-wars-episode-v-the-empire-strikes-back-darth-vader-205c0af116534c39844e3b87544ed4b9.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 7,
		name: 'Djoker',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://m.media-amazon.com/images/M/MV5BMGQ1ZGZmNTAtM2MyYi00NmZhLTkwYmYtNTNlZDRhMzU2ZTgwXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://m.media-amazon.com/images/M/MV5BMGQ1ZGZmNTAtM2MyYi00NmZhLTkwYmYtNTNlZDRhMzU2ZTgwXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
			'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdkayV4b9FmXgoLlMGMjjxe74nBmOjIyK8Eg&s',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 8,
		name: 'Doctor Strange',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://cdn.marvel.com/content/1x/doctorstrange_lob_mas_hlf_01_3.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://cdn.marvel.com/content/1x/doctorstrange_lob_mas_hlf_01_3.jpg',
			'https://www.pluggedin.com/wp-content/uploads/2022/05/Dr-Strange-in-the-Multiverse-of-Madness.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 9,
		name: 'Spider',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 1000,
		img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Spiderman.JPG/640px-Spiderman.JPG',
		piece: 'В наличии: 3',
		thumbnails: [
			'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Spiderman.JPG/640px-Spiderman.JPG',
			'https://cdn-uploads.gameblog.fr/img/news/425341_645e546f4ddec.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 10,
		name: 'Batman',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 800,
		img: 'https://media1.popsugar-assets.com/files/thumbor/rThpfVdJzMRcQWvlnlbskYGUSSU=/fit-in/792x528/top/filters:format_auto():upscale()/2022/03/04/966/n/1922283/tmp_YDoQMc_eba3e322cfc57f83_MCDBATM_WB059.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://media1.popsugar-assets.com/files/thumbor/rThpfVdJzMRcQWvlnlbskYGUSSU=/fit-in/792x528/top/filters:format_auto():upscale()/2022/03/04/966/n/1922283/tmp_YDoQMc_eba3e322cfc57f83_MCDBATM_WB059.jpg',
			'https://imageio.forbes.com/blogs-images/davidthier/files/2015/06/maxresdefault1.jpg?height=400&width=711&fit=bounds',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 11,
		name: 'Superman',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 700,
		img: 'https://images.immediate.co.uk/production/volatile/sites/3/2022/12/MCDBAVVEC017-d4ece24.jpg?quality=90&resize=980,654',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://images.immediate.co.uk/production/volatile/sites/3/2022/12/MCDBAVVEC017-d4ece24.jpg?quality=90&resize=980,654',
			'https://ew.com/thmb/IWTSy6GrKCmZBSIcZwC84oHmNdw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mos-10175c_2-2000-116d947875b84ddcabb01baa1fa1b389.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 12,
		name: 'Capitan America',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/05/hipertextual-avengers-endgame-futuro-capitan-america-2019781893-scaled.jpg?fit=2560%2C1600&quality=50&strip=all&ssl=1',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/05/hipertextual-avengers-endgame-futuro-capitan-america-2019781893-scaled.jpg?fit=2560%2C1600&quality=50&strip=all&ssl=1',
			'https://media-assets.wired.it/photos/615f38375b820b8db3e7d14b/master/w_1600%2Cc_limit/1538729691_25CHRISEVANS4-jumbo.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 13,
		name: 'Thor',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://cdn.britannica.com/73/182873-050-E1C686F4/Chris-Hemsworth-Thor-Thor-The-Dark-World.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://cdn.britannica.com/73/182873-050-E1C686F4/Chris-Hemsworth-Thor-Thor-The-Dark-World.jpg',
			'https://images.squarespace-cdn.com/content/v1/5fbc4a62c2150e62cfcb09aa/1621312752468-LNQ5D4XJNMZ0UOCDGEH1/Thor.png',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 14,
		name: 'Dart Vader',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://lumiere-a.akamaihd.net/v1/images/image_67b709e4.jpeg?region=0,0,1536,864&width=768',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://lumiere-a.akamaihd.net/v1/images/image_67b709e4.jpeg?region=0,0,1536,864&width=768',
			'https://ew.com/thmb/DR9B7S2D_xzQSnXZKvy7E1-9BKA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/star-wars-episode-v-the-empire-strikes-back-darth-vader-205c0af116534c39844e3b87544ed4b9.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 15,
		name: 'Djoker',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://m.media-amazon.com/images/M/MV5BMGQ1ZGZmNTAtM2MyYi00NmZhLTkwYmYtNTNlZDRhMzU2ZTgwXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://m.media-amazon.com/images/M/MV5BMGQ1ZGZmNTAtM2MyYi00NmZhLTkwYmYtNTNlZDRhMzU2ZTgwXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
			'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdkayV4b9FmXgoLlMGMjjxe74nBmOjIyK8Eg&s',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
	{
		id: 16,
		name: 'Doctor Strange',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates magni, facere fugit autem eum necessitatibus mollitia quis voluptate doloremque maxime temporibus nulla eveniet molestias non perspiciatis quaerat repudiandae dolores dolore distinctio ipsam. Possimus fugit impedit, maiores reprehenderit fugiat, quisquam iure alias quod, voluptatibus ipsa nostrum adipisci et. Placeat, quo sequi?',
		size: '48-52',
		price: 900,
		img: 'https://cdn.marvel.com/content/1x/doctorstrange_lob_mas_hlf_01_3.jpg',
		piece: 'Нет в наличии',
		thumbnails: [
			'https://cdn.marvel.com/content/1x/doctorstrange_lob_mas_hlf_01_3.jpg',
			'https://www.pluggedin.com/wp-content/uploads/2022/05/Dr-Strange-in-the-Multiverse-of-Madness.jpg',
		],
		ops: 'Дарт Ве́йдер, также известный под своим настоящим именем как Э́накин Скайуо́кер — центральный персонаж первых шести эпизодов саги «Звёздные войны». Также появляется в фильме «Изгой-один»Персонаж придуман Джорджем Лукасом. По одной из версий, имя Энакин скопировано с фамилии друга Лукаса — режиссёра Кена Эннакина[3], однако сам Лукас это опроверг на следующий же день после смерти Кена[4]. Многие Лорды Ситхов добавляли приставку «Дарт» к своим именам, и постепенно из-за количества «Дартов» она стала ассоциироваться с тёмной стороной Силы. Также эта приставка бралась как символ отказа от прежней жизни. Примером этого служит и Энакин Скайуокер, ставший Дартом Вейдером. Однако, само происхождение слова до сих пор остаётся неопределённым: большинство считает, что «Дарт» (англ. Darth) — это просто сокращение от «Тёмный лорд ситхов» (англ. Dark Lord of the Sith), но существуют теории, предполагающие более глубокую интерпретацию. ',
	},
];
